 baseurl: "/FoC"
url: "adolfomunoz.github.io"

source              : .
destination         : ./jekyll_site
collections_dir     : .
plugins_dir         : jekyll/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : jekyll/_layouts
data_dir            : jekyll/_data
includes_dir        : jekyll/_includes
sass:
  sass_dir: jekyll/_sass
  
collections:
  slides:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: slides
    values:
      layout: slide
