baseurl: "/FoC"
url: "adolfomunoz.github.io"

source              : .
destination         : ./jekyll/_site
collections_dir     : .
plugins_dir         : jekyll/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : jekyll/_layouts
data_dir            : jekyll/_data
includes_dir        : .
  
collections:
  slides:
    output: true
    permalink: /:collection/:name/
  assignments:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: slides
    values:
      layout: slide
  - scope:
      path: ""
      type: assignments
    values:
      layout: assignment

exclude: [external/reveal.js/test/simple.md, external/reveal.js-plugin-externalcode/README.md, external/reveal.js/css/theme/README.md, external/reveal.js/examples/markdown.md]

course: Fundamentals on Computing for Robotics, Graphics and Computer Vision
logo: img/unizar-logo.png
author: Darío Suárez - Adolfo Muñoz
frontpage: img/programming.jpg